"use client";
import React, { useState, useRef } from "react";
import { QRCodeCanvas } from "qrcode.react";
import {
  Download,
  Globe,
  Palette,
  Type,
  ShieldCheck,
  Image as ImageIcon,
  MessageCircle,
  Wifi,
  Mail,
  Copy,
  Check,
  AlertCircle,
} from "lucide-react";

type FeatureProps = {
  icon: React.ReactNode;
  title: string;
  desc: string;
};

export default function QRCodeClient() {
  const [text, setText] = useState("https://toolking.online");
  const [businessName, setBusinessName] = useState("TOOLKING PRO");
  const [fgColor, setFgColor] = useState("#15803d");
  const [includeLogo, setIncludeLogo] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // 🔥 FIX 7: UseRef for specific canvas targeting
  const qrRef = useRef<HTMLCanvasElement>(null);

  const handleCopyLink = () => {
    if (!text.trim()) return;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // 🔥 FIX 6: Presets for high-value traffic
  const applyPreset = (type: "wa" | "wifi" | "mail") => {
    if (type === "wa")
      setText("https://wa.me/919000000000?text=Hello%20ToolKing");
    if (type === "mail") setText("mailto:hello@toolking.online?subject=Query");
    if (type === "wifi") setText("WIFI:S:MyNetwork;T:WPA;P:password123;;");
  };

  const downloadQR = () => {
    // 🔥 FIX 4: Error Handling
    if (!text.trim()) {
      setError("Please enter a valid URL or text content.");
      return;
    }
    setError(null);

    const canvas = qrRef.current;
    if (!canvas) return;

    const finalCanvas = document.createElement("canvas");
    const ctx = finalCanvas.getContext("2d");
    if (!ctx) return;

    // 🔥 FIX 3: High-Res Resolution Logic
    const padding = 80;
    const textSpace = 120;
    finalCanvas.width = canvas.width + padding * 2;
    finalCanvas.height = canvas.height + padding + textSpace;

    // Background
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, finalCanvas.width, finalCanvas.height);

    // Draw QR
    ctx.drawImage(canvas, padding, padding);

    // Business Name
    ctx.fillStyle = "#0f172a";
    ctx.font = "bold 42px system-ui, sans-serif";
    ctx.textAlign = "center";
    ctx.fillText(
      businessName.toUpperCase(),
      finalCanvas.width / 2,
      canvas.height + padding + 50,
    );

    // Subtext
    ctx.fillStyle = "#94a3b8";
    ctx.font = "bold 14px system-ui, sans-serif";
    ctx.letterSpacing = "5px";
    ctx.fillText(
      "GENERATED BY TOOLKING.ONLINE",
      finalCanvas.width / 2,
      canvas.height + padding + 90,
    );

    const url = finalCanvas.toDataURL("image/png", 1.0);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${businessName.toLowerCase().replace(/\s+/g, "-")}-qr.png`;
    link.click();
  };

  return (
    <div className="grid lg:grid-cols-2 gap-12 items-start animate-in fade-in duration-700">
      <div className="space-y-8 bg-white dark:bg-slate-900 p-8 rounded-[3rem] border border-slate-100 dark:border-slate-800 shadow-2xl">
        {/* PRESETS SECTION */}
        <div className="flex gap-2 mb-2">
          <PresetBtn
            onClick={() => applyPreset("wa")}
            icon={<MessageCircle className="w-3 h-3" />}
            label="WhatsApp"
          />
          <PresetBtn
            onClick={() => applyPreset("wifi")}
            icon={<Wifi className="w-3 h-3" />}
            label="WiFi"
          />
          <PresetBtn
            onClick={() => applyPreset("mail")}
            icon={<Mail className="w-3 h-3" />}
            label="Email"
          />
        </div>

        <div className="space-y-6">
          <InputGroup
            label="Business Name"
            icon={<Type className="w-3 h-3" />}
            value={businessName}
            onChange={setBusinessName}
            placeholder="e.g. ToolKing Shop"
          />

          <div className="relative">
            <InputGroup
              label="QR Content / URL"
              icon={<Globe className="w-3 h-3" />}
              value={text}
              onChange={setText}
              placeholder="https://..."
            />
            <button
              onClick={handleCopyLink}
              className="absolute right-4 bottom-3 p-2 text-slate-400 hover:text-emerald-500 transition-colors"
            >
              {copied ? (
                <Check className="w-4 h-4" />
              ) : (
                <Copy className="w-4 h-4" />
              )}
            </button>
          </div>
        </div>

        <div className="flex gap-6 items-center pt-4 border-t border-slate-100 dark:border-slate-800">
          <div className="flex-1">
            <label className="text-[10px] font-black uppercase tracking-widest text-slate-400 mb-2 block">
              Brand Color
            </label>
            <input
              type="color"
              value={fgColor}
              onChange={(e) => setFgColor(e.target.value)}
              className="w-full h-12 rounded-xl cursor-pointer bg-transparent border-none"
            />
          </div>
          <button
            onClick={() => setIncludeLogo(!includeLogo)}
            className={`flex-1 h-12 rounded-xl border-2 border-dashed transition-all text-[10px] font-black uppercase tracking-widest ${includeLogo ? "border-emerald-500 bg-emerald-50 text-emerald-600" : "border-slate-200 text-slate-400"}`}
          >
            {includeLogo ? "Logo Active" : "Add Logo"}
          </button>
        </div>

        {error && (
          <div className="p-3 bg-rose-50 border border-rose-100 text-rose-600 text-[10px] font-bold rounded-xl flex items-center gap-2 animate-shake">
            <AlertCircle className="w-3 h-3" />
            {error}
          </div>
        )}
      </div>

      <div className="flex flex-col items-center">
        <div className="p-10 bg-white rounded-[4rem] shadow-2xl mb-10 text-center border border-slate-50">
          <div className="p-4 bg-slate-50 rounded-[2.5rem] mb-6 inline-block">
            {/* 🔥 FIX 3 & 7: High Res + Ref */}
            <QRCodeCanvas
              ref={qrRef}
              value={text || " "}
              size={512}
              style={{ width: 260, height: 260 }} // Visual size remains same, export is 512px
              level={"H"}
              fgColor={fgColor}
              marginSize={1}
              imageSettings={
                includeLogo
                  ? { src: "/logo.png", height: 80, width: 80, excavate: true }
                  : undefined
              }
            />
          </div>
          <h3 className="text-2xl font-black text-slate-900 tracking-tight">
            {businessName}
          </h3>
          <p className="text-[10px] font-black text-slate-400 tracking-[0.4em] mt-2 uppercase">
            Scan to Connect
          </p>
        </div>

        <button
          onClick={downloadQR}
          className="w-full max-w-xs py-5 bg-slate-900 text-white rounded-2xl font-black text-xs uppercase tracking-widest hover:bg-black transition-all shadow-2xl flex items-center justify-center gap-3"
        >
          <Download className="w-5 h-5" /> Export High-Res PNG
        </button>
      </div>
    </div>
  );
}

// 🔥 FIX 2: Type-Safe Components
function Feature({ icon, title, desc }: FeatureProps) {
  return (
    <div className="flex gap-4 p-4 rounded-2xl bg-slate-50 dark:bg-slate-900/50 border border-slate-100 dark:border-slate-800">
      <div className="mt-1">{icon}</div>
      <div>
        <p className="font-bold text-slate-900 dark:text-white">{title}</p>
        <p className="text-sm text-slate-500">{desc}</p>
      </div>
    </div>
  );
}

function InputGroup({ label, icon, value, onChange, placeholder }: any) {
  return (
    <div>
      <label className="flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-slate-400 mb-3">
        {icon}
        {label}
      </label>
      <input
        type="text"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        className="w-full px-6 py-4 rounded-2xl bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 focus:border-emerald-500 outline-none transition-all font-bold"
      />
    </div>
  );
}

function PresetBtn({ onClick, icon, label }: any) {
  return (
    <button
      onClick={onClick}
      className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-slate-100 dark:bg-slate-800 text-[10px] font-black text-slate-500 hover:bg-indigo-500 hover:text-white transition-all uppercase tracking-tighter"
    >
      {icon}
      {label}
    </button>
  );
}
